---
- name: Safe Cluster Update
  hosts: k3s_cluster
  become: yes
  serial: 1

  tasks:
    - name: Update apt repo cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot node is kernel updated
      reboot:
        msg: "Rebooting for updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: reboot_required_file.stat.exists
      
